---

- hosts: all
  become: true
  tasks:

  - name: remove apache2 package
    apt:
      name: apache2
      state: absent

  - name: remove php support for apache
    apt:
      name: libapache2-mod-php
      state: absent

  - name: remove samba 
    apt:
      name: samba
      state: absent

  - name: remove mamariadb
    apt:
      name: mariadb-server
      state: absent


